services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    environment:
      - WATCHFILES_FORCE_POLLING=true
    dns:               # <--- Add this block to fix DNS resolution inside Docker
      - 8.8.8.8
      - 8.8.4.4
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8501:80"
    depends_on:
      - backend